"""
Cursor IDE integration.

Generates .cursorrules configuration for Cursor AI editor.
"""

from pathlib import Path
from typing import Dict, Any, Optional

from .base import IDEIntegration


class CursorIntegration(IDEIntegration):
    """Cursor integration."""

    @property
    def name(self) -> str:
        return "Cursor"

    @property
    def config_file_path(self) -> Path:
        return self.spoke_dir / '.cursorrules'

    def detect(self) -> bool:
        """Detect if Cursor is being used."""
        has_cursorrules = self.config_file_path.exists()
        has_cursor_dir = (self.spoke_dir / '.cursor').exists()

        return has_cursorrules or has_cursor_dir

    def get_capabilities(self) -> Dict[str, Any]:
        """Get Cursor capabilities."""
        return {
            'supports_custom_instructions': True,
            'supports_file_watching': True,
            'supports_hooks': False,
            'supports_agent_mode': True,
            'context_window': 200000,  # Claude Sonnet 4 via Cursor
            'supports_images': True,
            'supports_composer': True  # Cursor's multi-file editing
        }

    def generate_config(self, template_vars: Optional[Dict[str, Any]] = None) -> str:
        """Generate .cursorrules configuration."""

        # Read WAI-Guide.md
        guide_file = self.wai_spoke_dir / 'WAI-Guide.md'
        guide_summary = ""
        if guide_file.exists():
            # Extract key sections from guide
            guide_content = guide_file.read_text()
            # Truncate if too long (Cursor has limits)
            if len(guide_content) > 5000:
                guide_summary = guide_content[:5000] + "\n\n... (truncated - see WAI-Spoke/WAI-Guide.md for full instructions)"
            else:
                guide_summary = guide_content

        # Read project info
        state_file = self.wai_spoke_dir / 'WAI-State.json'
        import json
        state = {}
        if state_file.exists():
            with open(state_file) as f:
                state = json.load(f)

        project_name = state.get('wheel', {}).get('name', 'Project')

        config = f"""# Cursor Rules for {project_name}

## Wheelwright Integration

This project uses Wheelwright for AI context persistence.

### Session Start Protocol

1. **Load Context**:
   - Read `WAI-Spoke/WAI-Guide.md` for full instructions
   - Read `WAI-Spoke/WAI-State.json` for project state
   - Read `WAI-Spoke/WAI-State.md` for strategic vision

2. **Brief User**:
   - Show project status
   - Show current phase and next actions
   - Check for uncommitted work (git status)

### Behavioral Guidelines

- Follow stewardship philosophy from WAI-Guide.md
- Log high-impact decisions (impact >= 8) to decisions array
- Update session state when making significant changes
- Track conversation in WAI-Session-Log.jsonl

### Complexity Gate (Planning Required)

If the task affects 2+ files or requires 6+ steps:
- Stay in discussion mode until the user says "READY TO PLAN"
- Propose a structured plan
- Wait for "PLAN ACCEPTED" before implementation

### Session Commands

- **Time**: Check token usage and capacity
- **Closeout**: End session with smart processing
- **Shipit**: Closeout + git commit

### Key Instructions

{guide_summary}

---

*Auto-generated by Wheelwright IDE integration*
"""

        return config

    def write_config(self, content: Optional[str] = None) -> Path:
        """Write .cursorrules to project root."""
        if content is None:
            content = self.generate_config()

        self.config_file_path.write_text(content)
        return self.config_file_path
