"""
Web LLM integration.

Generates context instructions for web-based LLMs (Claude.ai, ChatGPT, Grok, etc.)
"""

from pathlib import Path
from typing import Dict, Any, Optional

from .base import IDEIntegration


class WebLLMIntegration(IDEIntegration):
    """Web-based LLM integration."""

    @property
    def name(self) -> str:
        return "Web LLM"

    @property
    def config_file_path(self) -> Path:
        return self.wai_spoke_dir / 'WAI-WebLLM-Instructions.md'

    def detect(self) -> bool:
        """
        Web LLMs can't be auto-detected.
        This is a fallback integration.
        """
        return False

    def get_capabilities(self) -> Dict[str, Any]:
        """Get generic web LLM capabilities."""
        return {
            'supports_custom_instructions': True,
            'supports_file_watching': False,
            'supports_hooks': False,
            'context_window': 'varies',
            'supports_copy_paste': True,
            'platforms': ['Claude.ai', 'ChatGPT', 'Grok', 'Perplexity', 'Gemini']
        }

    def generate_config(self, template_vars: Optional[Dict[str, Any]] = None) -> str:
        """Generate web LLM instructions."""

        # Read project info
        state_file = self.wai_spoke_dir / 'WAI-State.json'
        import json
        state = {}
        if state_file.exists():
            with open(state_file) as f:
                state = json.load(f)

        project_name = state.get('wheel', {}).get('name', 'Project')
        project_description = state.get('wheel', {}).get('description', '')

        config = f"""# Web LLM Instructions for {project_name}

**This project uses Wheelwright for AI context persistence.**

## How to Use This Project with Web LLMs

### Step 1: Load Context

Copy and paste the following files into your conversation:

1. **WAI-Spoke/WAI-Guide.md** - Full AI instructions and protocols
2. **WAI-Spoke/WAI-State.json** - Current project state and decisions
3. **WAI-Spoke/WAI-State.md** - Strategic vision and evolution

Or use: `cat WAI-Spoke/WAI-Guide.md WAI-Spoke/WAI-State.md` and paste the output.

### Step 2: Session Start

After loading context, say:

> "I've loaded the Wheelwright context for {project_name}. Please brief me on the current status and next actions."

The AI will:
- Summarize project status
- Show current phase
- List next actions
- Check for uncommitted work

### Step 3: Work on the Project

The AI will follow the guidelines in WAI-Guide.md including:
- Stewardship philosophy (AI as responsible partner)
- Decision logging for high-impact choices
- Session state management

### Complexity Gate (Planning Required)

If the task affects 2+ files or requires 6+ steps:
- Stay in discussion mode until the user says "READY TO PLAN"
- Propose a structured plan
- Wait for "PLAN ACCEPTED" before implementation

### Step 4: End Session

When done, say:

> "Closeout"

The AI will provide:
- Session summary
- Updated WAI-State.json content (copy back to file)
- Decisions to record
- Next session recommendations

### Session Commands

During your session, you can use these commands:

- **'Time'** - Check token usage and context capacity
- **'Compact'** - Compress context by summarizing
- **'Closeout'** - End session and get updated state files
- **'Shipit'** - Closeout + git commit instructions

## Project Context

**Name:** {project_name}
**Description:** {project_description}

**See WAI-Spoke/ for complete context.**

---

## Quick Start Template

```
I'm working on a Wheelwright-enabled project. I've loaded the context from WAI-Spoke/.

Please:
1. Brief me on the current project status
2. Show me the current phase and next actions
3. Check git status for uncommitted work

Then let's continue where we left off.
```

---

*Auto-generated by Wheelwright IDE integration*
*For CLI-based workflows, see Claude Code or Cursor integration instead*
"""

        return config

    def write_config(self, content: Optional[str] = None) -> Path:
        """Write instructions to WAI-Spoke/."""
        if content is None:
            content = self.generate_config()

        self.config_file_path.write_text(content)
        return self.config_file_path
